### PR TITLE
fix cabal build, better portability

### PR DESCRIPTION
**Pull request by bfrk**

### CODE REVIEW

**Comment by adamsmasher** [comment]
Hi! Thanks for the PR. Someone did something similar a few years back (see #2) and...it looks like I just forgot about it. Oops.

I'll repeat what I [wrote](https://github.com/adamsmasher/hs-cdb/pull/2#issuecomment-421157829) there - this library is ancient and was written when I was very junior and probably shouldn't be used. The author of that other PR [switched](https://github.com/adamsmasher/hs-cdb/pull/2#issuecomment-421947585) to a different library called pure-cdb that I will assume is better.

Anyway, I am going to go ahead and merge this. Thanks again! In the event that you find/are finding this library useful, I'm glad 🙂

**Comment by bfrk** [comment]
Thanks for merging my changes. Can you upload a release to hackage?

I am pretty sure it will be useful to me, though I am still experimenting with it. As almost anything done by DJB the cdb idea and design are brilliant. And I like that your package has such a small and easy API (and not much code either).

**Comment by adamsmasher** [comment]
@bfrk OK, a new version should be out on Hackage! It was released as version 0.1.2. Let me know if it you run into any difficulties with it.

**Comment by bfrk** [comment]
Thanks!

**Pull request merged**
